require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'app/models/concerns/sufia/file_set/export.rb'

Lint/ImplicitStringConcatenation:
  Exclude: []

Metrics/LineLength:
  Enabled: true
  Max: 100
  Exclude:
    - 'config/routes.rb'
    - 'spec/routing/**/*'
    # only because the solr name generators are very long-named
    - 'app/controllers/catalog_controller.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude: []

Metrics/PerceivedComplexity:
  Exclude: []

Metrics/MethodLength:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    # exclude until we have a better DSL for the Blacklight config
    - 'app/controllers/catalog_controller.rb'

Metrics/ModuleLength:
  Exclude: []

Performance/RedundantMerge:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude: []

Style/LineEndConcatenation:
  Exclude: []

Style/PredicateName:
  Exclude: []

Style/GlobalVars:
  Exclude:
    # pending https://github.com/projecthydra/sufia/issues/1599
    - 'lib/sufia/redis_config.rb'
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude: []

Style/SignalException:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/HasAndBelongsToMany:
  Exclude: []

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude: []